require: rubocop-rails
AllCops:
  TargetRubyVersion: 2.6.3
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'log/**/*'
    - 'spec/support/**/*'
    - 'app/helpers/devise_helper.rb'
Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'
Metrics/LineLength:
  Max: 120
Metrics/BlockLength:
  Max: 130
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/MutableConstant:
  Enabled: false
